version: '3.8'

services:
  db-maria:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: CESI-eats
    network_mode: host
  db-mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: CESI-eats
    network_mode: host

